export enum Token {
  USER_REPOSITORY = "USER_REPOSITORY",
  COOKIES_SERVICE = "COOKIES_SERVICE",
  POST_REPOSITORY = "POST_REPOSITORY",
  PROPOSAL_REPOSITORY = "PROPOSAL_REPOSITORY",
  DRAFT_REPOSITORY = "DRAFT_REPOSITORY",
  AUTH_REPOSITORY = "AUTH_REPOSITORY",
}
